/* Generated By:JJTree: Do not edit this line. AstDotSuffix.java */

package org.jboss.el.parser;

public class AstDotSuffix extends SimpleNode {
  public AstDotSuffix(int id) {
    super(id);
  }

}
